const activities = [
  { name: 'Flashlight Tag', category: 'outdoors', icon: '🔦', description: 'Hide, giggle, and glow in the dark.', why: 'Everything feels more exciting after sunset—and the flashlight makes you the star.', how: 'Wait until it is safely getting dark, grab a grown-up, then play tag with flashlights in a familiar yard or park.', try: 'Try “statue tag”: when the beam finds you, freeze until a friend unfreezes you.' },
  { name: 'Sidewalk Safari', category: 'outdoors', icon: '🦋', description: 'Walk like the animals you spot.', why: 'A regular walk becomes a little adventure when there is something to look for.', how: 'Choose a safe route and make a list: birds, leaves, dogs, bugs, clouds. Move like each one when you find it.', try: 'Can you find five things in every color of the rainbow?' },
  { name: 'Puddle Jump', category: 'outdoors', icon: '💦', description: 'Rainy-day leaps with a splash.', why: 'It is hard to take puddles seriously, which is exactly the point.', how: 'Put on rain boots, choose shallow puddles with a grown-up, and make up your own jump challenges.', try: 'Give every jump a score for splashiness, not style.' },
  { name: 'Chalk Quest', category: 'outdoors', icon: '🖍️', description: 'Draw a path, then play on it.', why: 'You get to make the rules and change them whenever you want.', how: 'Draw dots, zigzags, circles, and a finish line on pavement. Hop, tiptoe, crab-walk, or spin between them.', try: 'Let a friend add one silly new rule to your path.' },
  { name: 'Tree Trail', category: 'outdoors', icon: '🌳', description: 'A low-key nature scavenger hunt.', why: 'There is no race—just wandering, noticing, and collecting cool memories.', how: 'Walk a trail or park path and hunt for a smooth rock, a twisty stick, a tiny flower, and a bird sound.', try: 'Make up a secret name for every tree you pass.' },
  { name: 'Breeze Chaser', category: 'outdoors', icon: '🪁', description: 'Run with ribbons or a kite.', why: 'The wind does some of the work, and watching things fly is magic.', how: 'Find an open space, hold a ribbon or fly a kite with help, and follow where the breeze pulls you.', try: 'Can you make your ribbon draw a giant letter in the air?' },
  { name: 'Music Freeze', category: 'indoors', icon: '🎵', description: 'Dance, stop, make a weird pose.', why: 'There is no dance to learn—your weirdest move is probably the best one.', how: 'Put on any song. Dance until someone pauses it, then freeze exactly where you are.', try: 'Each round has a theme: jelly, robot, sleepy bear, spaghetti.' },
  { name: 'Blanket Fort Crawl', category: 'indoors', icon: '🏕️', description: 'Turn your room into an obstacle course.', why: 'A fort makes even crawling feel like exploring a secret world.', how: 'With permission, make a blanket tunnel over chairs. Crawl through, circle a pillow mountain, then return.', try: 'Deliver a stuffed animal “package” through the tunnel without dropping it.' },
  { name: 'Balloon Keep-Up', category: 'indoors', icon: '🎈', description: 'Keep it floating—anything goes.', why: 'A balloon floats slowly enough that everybody gets a chance.', how: 'Tap a balloon before it hits the floor. Use hands, elbows, knees, or even your head.', try: 'How many taps can you get using no hands?' },
  { name: 'Socks Slide', category: 'indoors', icon: '🧦', description: 'Glide across a safe floor.', why: 'It feels like being a tiny ice skater in your own home.', how: 'On a clear, dry, smooth floor, slide gently in socks. Keep furniture and sharp corners far away.', try: 'Make a three-move slide routine with a finishing pose.' },
  { name: 'Animal Parade', category: 'indoors', icon: '🦀', description: 'Walk, crawl, and stomp like animals.', why: 'Pretending means you get to be strong, sneaky, slow, or very silly.', how: 'Pick an animal and travel across the room: bear crawl, flamingo balance, crab walk, elephant stomp.', try: 'Make a story that needs three different animals to act it out.' },
  { name: 'Mirror Moves', category: 'indoors', icon: '🪞', description: 'Copy your own funny reflection.', why: 'It is private, creative, and a great way to see what your body can do.', how: 'Stand in front of a mirror and make slow shapes, big stretches, and goofy faces.', try: 'Try moving in slow motion like you are underwater.' },
  { name: 'Secret Handshake', category: 'friends', icon: '🤝', description: 'Invent a move only your crew knows.', why: 'It is movement that feels like an inside joke.', how: 'With a friend, string together claps, spins, fist bumps, steps, and poses.', try: 'Teach your handshake to someone new without using any words.' },
  { name: 'Shadow Chase', category: 'friends', icon: '👥', description: 'Tag shadows, not people.', why: 'It is tag with a twist and no one has to run super fast.', how: 'On a sunny day, try stepping on each other’s shadows. Switch who is “it” every minute.', try: 'Move like a giant, a tiny mouse, or a superhero to change your shadow.' },
  { name: 'Dance Battle', category: 'friends', icon: '💃', description: 'Show off your silliest 10 seconds.', why: 'There are no judges—just cheering for each other.', how: 'Take turns dancing for ten seconds while everyone else copies the last move.', try: 'Pick a ridiculous theme: breakfast, aliens, or underwater disco.' },
  { name: 'Pass the Pose', category: 'friends', icon: '🕺', description: 'Copy, add, repeat.', why: 'Every person adds one little piece, so the final dance belongs to everyone.', how: 'The first person makes a pose. The next copies it and adds another. Keep building.', try: 'See if you can remember a chain of 12 poses.' },
  { name: 'Treasure Relay', category: 'friends', icon: '🗺️', description: 'A teamwork hunt, not a race.', why: 'The fun part is finding clues together—not being first.', how: 'Hide friendly clues around a room or yard. Take turns doing a playful move to reach each clue.', try: 'Make clues that rhyme or include a funny sound effect.' },
  { name: 'Wobble Walk', category: 'other', icon: '〰️', description: 'Follow the squiggly line.', why: 'Balance gets easier when it feels like a game instead of practice.', how: 'Tape or draw a wavy line. Follow it forward, backward, sideways, or with your eyes on a stuffed animal.', try: 'Add “islands” where you have to balance for three seconds.' },
  { name: 'Living Room Lava', category: 'other', icon: '🌋', description: 'Hop from safe spot to safe spot.', why: 'Your imagination turns ordinary cushions into an epic mission.', how: 'Set out pillows or paper spots with permission. Travel between them without touching the “lava.”', try: 'Carry a toy explorer to safety on your hardest route.' },
  { name: 'Pajama Stretch', category: 'other', icon: '🌙', description: 'Slow stretches before bed.', why: 'Quiet movement can help your body settle down after a big day.', how: 'Reach tall, fold gently, circle your shoulders, and curl into a cozy ball. Keep it comfortable.', try: 'End by taking three slow balloon breaths.' },
  { name: 'Hopscotch Remix', category: 'outdoors', icon: '🔢', description: 'The classic, with your own rules.', why: 'You can make it as easy, wild, or creative as you want.', how: 'Draw a hopscotch board, then replace numbers with colors, animals, or favorite snacks.', try: 'Land on blue? Do a penguin waddle to the next square.' },
  { name: 'Laundry Basket Toss', category: 'indoors', icon: '🧺', description: 'Toss soft socks into a target.', why: 'It gives you a goal without needing a fancy game or perfect aim.', how: 'Roll socks into balls and place a basket a few steps away. Toss, move it, and try again.', try: 'Take a silly victory lap every time you score.' },
  { name: 'Make-Believe Mission', category: 'other', icon: '🚀', description: 'Move through a story you invent.', why: 'You are not exercising—you are escaping a moon monster or exploring a jungle.', how: 'Choose a mission. Crawl under lasers, leap over rivers, and tiptoe past sleeping dragons.', try: 'Ask someone to add the next part of your mission.' },
  { name: 'Hula Hoop Planet', category: 'friends', icon: '⭕', description: 'Spin, step, and play around hoops.', why: 'A hoop can be a planet, a portal, a steering wheel—whatever you imagine.', how: 'Put hoops on the ground and make up ways to travel between them together.', try: 'Everyone gets one turn inventing a rule.' },
  { name: 'Stair Step Beat', category: 'other', icon: '👟', description: 'Make a rhythm with your steps.', why: 'It turns a regular trip up or down into your own tiny music video.', how: 'On safe stairs with an adult nearby, step to a beat: slow-slow-fast, then change it.', try: 'Clap your rhythm before you try it with your feet.' },
  { name: 'Bubble Chase', category: 'outdoors', icon: '🫧', description: 'Pop, reach, and run through bubbles.', why: 'Bubbles do not care how coordinated you are. They just invite you to play.', how: 'Have someone blow bubbles in an open, safe spot. Chase, pop, and count the biggest ones.', try: 'Try to pop bubbles with your elbow, shoulder, or toes.' },
  { name: 'Paper Airplane Run', category: 'friends', icon: '✈️', description: 'Fly, fetch, fold, repeat.', why: 'Every flight is a surprise, and you get a reason to move between launches.', how: 'Fold paper planes, launch from a clear spot, then walk or run to collect them together.', try: 'Give your plane a name and make a dramatic launch announcement.' },
  { name: 'Garden Helper', category: 'outdoors', icon: '🌱', description: 'Water, dig, and explore outside.', why: 'Moving feels different when you are helping something grow.', how: 'Help water plants, pull a few weeds, or carry a small watering can with a grown-up.', try: 'Count how many different shades of green you can spot.' },
  { name: 'Copycat Comedy', category: 'friends', icon: '😄', description: 'Take turns making impossible-to-copy moves.', why: 'The harder it is to copy, the funnier it gets.', how: 'One person makes a silly move. Everyone tries it. Then choose the next leader.', try: 'Use only movements that start with the letter S.' }
];

const colors = ['#ddff66', '#ff6ea8', '#ff9b54', '#96e5fa', '#b8a2ff'];
const surpriseIndexes = [0, 3, 6, 8, 12, 17, 19, 22, 27];
function activityURL(index) { return `activity.html?move=${index}`; }
function buildHome() {
  const shoes = document.querySelector('#shoe-grid');
  const cards = document.querySelector('#activity-grid');
  if (!shoes || !cards) return;
  shoes.innerHTML = surpriseIndexes.map(i => `<a class="shoe" href="${activityURL(i)}" aria-label="Open a mystery move"><span class="question">?</span><span class="shoe-icon">👟</span></a>`).join('');
  const render = (filter = 'all') => { cards.innerHTML = activities.map((a, i) => ({a,i})).filter(({a}) => filter === 'all' || a.category === filter).map(({a,i}) => `<a class="activity-card" href="${activityURL(i)}"><span class="card-category">${a.category}</span><span class="card-icon">${a.icon}</span><span><h3>${a.name}</h3><p>${a.description}</p></span><span class="card-arrow">↗</span></a>`).join(''); };
  render();
  document.querySelectorAll('.filter').forEach(button => button.addEventListener('click', () => { document.querySelector('.filter.active').classList.remove('active'); button.classList.add('active'); render(button.dataset.filter); }));
}
function buildDetail() {
  const target = document.querySelector('#activity-detail'); if (!target) return;
  const index = Number(new URLSearchParams(location.search).get('move'));
  const a = activities[index] || activities[0]; const color = colors[index % colors.length];
  target.innerHTML = `<section class="detail" style="background:${color}"><a class="back" href="index.html#pick">← Back to home</a><div class="detail-content"><span class="tag">A ${a.category} move</span><div class="detail-icon">${a.icon}</div><h1>${a.name}</h1><div class="detail-copy"><div><h2>Why it’s fun</h2><p>${a.why}</p></div><div><h2>How it works</h2><p>${a.how}</p></div></div><p class="detail-try">TRY THIS: ${a.try}</p></div></section>`;
}
buildHome(); buildDetail();
